# Generated by Django 5.0.6 on 2024-05-15 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('turma', models.CharField(choices=[('K', 'Kids'), ('T', 'Teens'), ('A', 'Adulto'), ('I', 'Idosos')], max_length=1)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='A', max_length=1)),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Curso  ',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ementa', models.TextField(verbose_name='Ementa da Disciplina')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Aula')),
                ('sala', models.CharField(max_length=5, verbose_name='Sala de Aula')),
                ('observacoes', models.TextField(default='Aula Expositiva', verbose_name='Observações sobre a aula')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.idioma'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('I', 'Ativa - Iniciando'), ('A', 'Ativa - Em andamento'), ('C', 'Desativada - Concluída'), ('S', 'Desativada - Suspensa')], default='I', max_length=1)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='FrequenciaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aula')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.matricula')),
            ],
            options={
                'verbose_name': 'Frequencia Escolar',
                'verbose_name_plural': 'Frequencias Escolares',
            },
        ),
        migrations.CreateModel(
            name='BoletimEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_um', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 1')),
                ('nota_dois', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 2')),
                ('nota_tres', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 3')),
                ('nota_quatro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 4')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.matricula')),
            ],
            options={
                'verbose_name': 'BoletimEscolar',
                'verbose_name_plural': 'Boletins Escolares',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('idiomas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.idioma')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.professor'),
        ),
    ]
