# Generated by Django 5.0.6 on 2024-05-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
