# Generated by Django 5.0.6 on 2024-05-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='idiomas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.idioma'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('turma', models.CharField(choices=[('K', 'Kids'), ('T', 'Teens'), ('A', 'Adulto'), ('I', 'Idosos')], max_length=1)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.idioma')),
            ],
            options={
                'verbose_name': 'Curso  ',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=8, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
