# Generated by Django 5.0.6 on 2024-05-14 02:28

import django.db.models.deletion
import escola.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_idioma_options_curso_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='codigo',
            field=models.PositiveIntegerField(default=escola.models.gerar_codigo, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='idiomas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.idioma'),
        ),
    ]
