# Generated by Django 5.0.6 on 2024-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_idioma_options_aluno_email_aluno_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('I', 'Ativa - Iniciando'), ('A', 'Ativa - Em andamento'), ('C', 'Desativada - Concluída'), ('S', 'Desativada - Suspensa')], default='I', max_length=1),
        ),
    ]
