# Generated by Django 5.0.6 on 2024-05-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_curso_nivel_matricula_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletimEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_um', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 1')),
                ('nota_dois', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 2')),
                ('nota_tres', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 3')),
                ('nota_quatro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 4')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='boletim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.boletimescolar'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ementa', models.TextField(verbose_name='Ementa da Disciplina')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.professor')),
            ],
        ),
        migrations.AddField(
            model_name='boletimescolar',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Aula')),
                ('sala', models.CharField(max_length=5, verbose_name='Sala de Aula')),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escola.aula')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='frequencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.frequenciaescolar'),
        ),
    ]
