# Generated by Django 5.0.6 on 2024-05-14 02:31

import escola.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_aluno_email_aluno_telefone_professor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='codigo',
            field=models.CharField(default=escola.models.gerar_codigo, editable=False, max_length=8, unique=True),
        ),
    ]
