# Generated by Django 5.0.6 on 2024-05-14 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_boletimescolar_matricula_boletim_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaescolar',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aluno'),
        ),
    ]
