# Generated by Django 5.0.6 on 2024-05-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_frequenciaescolar_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='boletimescolar',
            options={'verbose_name': 'BoletimEscolar', 'verbose_name_plural': 'Boletins Escolares'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='frequenciaescolar',
            options={'verbose_name': 'Frequencia Escolar', 'verbose_name_plural': 'Frequencias Escolares'},
        ),
    ]
