# Generated by Django 5.0.6 on 2024-05-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_alter_aula_options_alter_boletimescolar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimescolar',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.disciplina'),
        ),
        migrations.AlterField(
            model_name='frequenciaescolar',
            name='aula',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.aula'),
        ),
    ]
