# Generated by Django 5.0.6 on 2024-05-15 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_boletimescolar_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
