# Generated by Django 5.0.6 on 2024-05-15 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_alter_matricula_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='id',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
